defaults:
  - _self_

extractor:
  _target_: torch.nn.Identity
encoder:
  _target_: src.models.components.yaapt_wrapper.YAAPTImplementationEncoder
decoder:
  _target_: src.models.components.yaapt_wrapper.YAAPTImplementationDecoder
  _partial_: true

_target_: src.models.pitch_module.PitchModule
criteria: 
  _target_: torch.nn.functional.cross_entropy
  _partial_: true
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00025
  
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 10
  threshold_mode: rel


# compile model for faster training with pytorch 2.0
compile: false

