defaults:
  - log_results
  - model_checkpoint
  - early_stopping
  - learning_rate_monitor
  - model_summary
  - rich_progress_bar
  - _self_
  - log_grad_norms

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/rca"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
