_target_: src.models.components.extractors.ParallelFeatureExtractor
XCorrExt:
  _target_: src.models.components.extractors.XCorrExt
  N: 320
  H: 160
  TAU: 257
IFExt:
  _target_: src.models.components.extractors.IFExt
  N: 320
  H: 160
  N_freq: 30

